name: Group27 DevOpsApp Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_codecheck:
    runs-on: ubuntu-latest

    steps: 
      - name: Checking out Repository
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Installing pylint
        run: pip install pylint flask

      - name: Running pylint
        run: pylint src/main/python/app.py

  build_and_test_stages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Installing pylint
        run: |
          python -m pip install --upgrade pip
          pip install pybuilder flask

      - name: Build and Test
        run: pyb

      - name: Uploading the Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/reports
